Consultation request pages
kir-dev/konzisite-frontend pull request #134
Opened 2023-02-23 14:59 UTC by kisbogdan-kolos

closes #13

2023-02-23 18:54 UTC, DannySS123 requested changes
Very nice job! 🥇 

Some problems:
- Konzi Request Törlés gomb does nothing
- too long name goes outside of the box, do what I did on the other pages
![image](https://user-images.githubusercontent.com/65909866/220999850-0faab971-2927-491e-b0f0-0ca1b9359ae1.png)
- there is a lot of empty space in a card:
![image](https://user-images.githubusercontent.com/65909866/221000226-49bb03f3-a5bc-4e40-aea1-4bc38f28696d.png)
maybe consider doing the 2 column grid as on the groupspage?
- there should be a "Megtartom" button on the RequestDetails page, that goes to a new consultation page with filled out data. This button can alse be on the cards in the requests list, than there won't be that much space and we won't need 2 columns.
- the new consultation page should have a field for "Megvalósított kérés" (perhaps a better name). If it's selected the data should be filled. 
There are many ways to do this, for example with a checkbox for completing a request and if it's checked and a request is selected, the filled out data (subject, etc..) should be disabled for editing, or enabled but then changing it will uncheck the checkbox and remove the selected request. These are just some ideas, experiment a bit and find a nice solution that is confortable to use.

This might seem a lot, but altogether, great work, you can be proud! We are too ❤️ 
If I left out anything @Tschonti will probobly mention it later xd

2023-02-23 18:54 UTC, DannySS123 commented on src/pages/requests/RequestListPage.tsx
> +      </Heading>
PageHeading

2023-02-23 18:54 UTC, DannySS123 commented on src/pages/requests/RequestDetailsPage.tsx
> +      </Heading>
PageHeading

2023-02-23 18:54 UTC, DannySS123 commented on src/components/commons/MajorAvatar.tsx
> +  let bgcolor = subject.majors.length > 1 ? 'purple.500' : majorColorForIcon[subject.majors[0]]
Multisubject color should stay orange
But feel free to experiment and find better colors for the subjects in a different pr :D

2023-02-23 19:05 UTC, Tschonti commented
I think the Konzi megtartása stuff can be a separate task for tomorrow. If you're interested, we can do it together. But this PR is pretty large already, those features should be handled separately (also, there a few additional stuff for those)

2023-02-23 22:30 UTC, kisbogdan-kolos commented
> I think the Konzi megtartása stuff can be a separate task for tomorrow. If you're interested, we can do it together. But this PR is pretty large already, those features should be handled separately (also, there a few additional stuff for those)

Okay. The 'konzi megtartása' button should be easy, I will include it here, and leave the other stuff for a different PR.

2023-02-23 23:17 UTC, DannySS123 approved these changes
Seems good 👌

2023-02-24 11:05 UTC, Tschonti approved these changes
Very nice job! I edited the layout of the buttons on the request list. Previously:
![image](https://user-images.githubusercontent.com/13004605/221163400-e22a2b6c-896a-4417-a6c5-fa652ccd5380.png)
Now:
![image](https://user-images.githubusercontent.com/13004605/221163408-4e2e228d-3832-4cfa-b3cb-6bbfd796968e.png)
(unchanged on smaller devices)

One idea: instead of showing the expiry date on the request list, we could just show how many days are left (or months, if it's far away). Just to make sure people don't confuse requests with konzis.

2023-02-24 11:35 UTC, kisbogdan-kolos commented on src/pages/requests/RequestDetailsPage.tsx
> +            ) : (
I copied this from the consultations list and forgot to delete it.

2023-02-24 12:48 UTC, merged